### ISSUE TITLE
Exception when calculating sub paths of empty Paths object

### ISSUE THREAD

**Issue by IngoScholtes** [IngoScholtes/pathpy#6]
Call of expandSubPaths on empty paths object raises exception

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/cluster/home/ingosc/Acyclic_Paths/src/pathpy/pathpy/Paths.py", line 298, in expandSubPaths
    for l in range(max(self.paths)):
ValueError: max() arg is an empty sequence
```

**Comment by IngoScholtes** [comment]
fixed in [bfdae4a](https://github.com/IngoScholtes/pathpy/commit/bfdae4a130aa92db38bff077b13bfd9ecb86d8af)
